site:
  title: "Akka Samples Site"
  url: https://akka.io/akka-samples
  
content:
  sources:
  - url: git@github.com:akka/akka-samples.git
    start-paths: 
      - docs/docs-source/docs
    branches: [2.6]

ui: 
  bundle:
    url: https://github.com/lightbend/antora-ui-lightbend-theme/raw/master/build/ui-bundle.zip
    snapshot: true
    
runtime:
  fetch: true

asciidoc:

  attributes:
    # the following two attributes cause review and todo notes to display
    # review: ''
    # todo: ''
    doc-title: 'Akka Samples'

output:
  dir: ./../target/staging
  clean: true
